language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: N1WuSqrwUxjMR9d7FgO7yK3rF57aEM+7A6Ddzyry8lHYx+DOKRdAKoQz27fXRUUXhsPVAdQIPcnZHjre27N1d80v+HJS9Fhx/OmFscOKevN+9eGIvf7iAingGwsVgfpMD2bpnvoNOhI+gM7euS2ZhMuARzDzgk3ewnM1fFXqtZrNvnqyW0u7IHeuw47nufbSUpAn23XDGTbrZzNlG51KG1Ajh+OIfDgpPuFO7cDPcZaWhs0o+WtiZpyfXwxyOw2QtHU39VGTZutc3kibo/zw8p4FVevJPpN+UO3YLu6f5aXFzZAjeXYOtiOX9nSgAFjx13vsJnpDgb+YmBStHhCb8gLaJTOvuDxYX9CJTHkAoC+scZBrqjK0LKwrd7aGE6pbgYYhK1tlb/5wIJSRZFvkZIxpZBJq02l+hDGtJ6lcSqApOJhDgcg0UyvwZUjtfaXoy+o6RUwgvMzOlpxJi4PjfT3gK8SC2GcYAWFPp88HJ1NP5vBk43b2Yz+WSHFjzY1pUU95pJESWNOujmHadwtD5MguXQCtFJriYfr+JtLmIIxverasolWg6qnPLtnsKh6Zi7gZ9wwsONv4uW8FwaEDDpo258PLkJ/Q5C8+leqRYfl+nNA9c98hCQjQYOwACXGsqkZhLXqPR21dz+mXcF1b77I5MQD0PkgHVeETNdBV0kY=
